# Generated by Django 4.2 on 2025-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_fname', models.CharField(max_length=50)),
                ('m_lname', models.CharField(max_length=50)),
                ('m_gender', models.CharField(max_length=50)),
                ('m_dob', models.DateField()),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
