# Generated by Django 4.2 on 2025-05-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_nid',
            field=models.IntegerField(default=119648009878778),
            preserve_default=False,
        ),
    ]
