# Generated by Django 4.2 on 2025-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_member_m_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='brower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('brow_date', models.DateField()),
                ('date_to_return', models.DateField()),
                ('returned_on', models.DateField(default=None)),
                ('decosion', models.CharField(default='No', max_length=5)),
            ],
            options={
                'db_table': 'brower',
            },
        ),
    ]
