# Generated by Django 4.2 on 2025-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_brower'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='p_number',
            field=models.IntegerField(default='0793458446'),
            preserve_default=False,
        ),
    ]
