# Generated by Django 4.2 on 2025-06-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_member_p_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brower',
            old_name='decosion',
            new_name='decision',
        ),
        migrations.AlterField(
            model_name='brower',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
        ),
        migrations.AlterField(
            model_name='brower',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.member'),
        ),
    ]
