# Generated by Django 4.2 on 2025-06-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_decosion_brower_decision_alter_brower_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brower',
            name='returned_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
